#cloud-config

groups:
  - Ubuntu: [root, sys]
  - cloud users

users:
  - name: transip
    groups: transip
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJwOybdYwdNeQ6USqOEz8h1wXVeiIZLa3S0vnxbc0sto jasper@imagewize.com
    sudo: ['ALL = (ALL) NOPASSWD: ALL']
    shell: /bin/bash

chpasswd:
  list: |
    root: your password

write_files:
- path: /etc/ssh/sshd_config
  permissions: 0600
  owner: root:root
  content: |
    Port 22

    HostKey /etc/ssh/ssh_host_rsa_key
    HostKey /etc/ssh/ssh_host_ecdsa_key
    HostKey /etc/ssh/ssh_host_ed25519_key

    SyslogFacility AUTHPRIV

    PermitRootLogin No

    AuthorizedKeysFile      .ssh/authorized_keys

    PasswordAuthentication no

    ChallengeResponseAuthentication no

    GSSAPIAuthentication yes
    GSSAPICleanupCredentials no

    UsePAM yes

    X11Forwarding yes

    AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
    AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
    AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE
    AcceptEnv XMODIFIERS

    Subsystem       sftp    /usr/libexec/openssh/sftp-server

runcmd:
  - sed -i "s/#Port 22/Port 12345/" /etc/ssh/sshd_config

packages:
  - packagename1
  - packagename2

phone_home:
  url: http://pxe.frontend.transip.nl/cloudinit/post-install
  post: []
  tries: 5